name: swaram_ai
description: Telugu Corpus AI
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  appwrite: ^12.0.1
  avatar_glow: ^3.0.1
  awesome_snackbar_content: ^0.1.3
  camera: ^0.10.6
  connectivity_plus: ^6.0.3
  flexi_chip: ^1.0.8
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.5
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  icons_plus: ^5.0.0
  logger: ^2.2.0
  lottie: ^3.1.0
  otp_text_field: ^1.1.3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  record: ^5.0.5
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  lints: ^3.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ai_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
